-- Migration: 0017_add_application_access_active_grant_unique
-- Direção: UP
-- Motor: MariaDB 10.11, InnoDB, utf8mb4, utf8mb4_unicode_520_ci
--
-- Referência: fundação do importador Helpdesk -> Ingressa (v0.8.x),
-- item 1 da task. Origem do achado: auditoria read-only do Helpdesk.
--
-- PROBLEMA QUE ESTA MIGRATION FECHA
--
-- `application_accesses` não tem NENHUMA constraint de unicidade sobre
-- (identity_public_id, application_public_id). A única proteção contra
-- acesso duplicado vive na aplicação:
-- `GrantApplicationAccessService` chama
-- `existsGrantedByIdentityApplicationAndProfile(...)` antes de inserir.
--
-- Dois furos reais nesse desenho:
--
--   1. A checagem inclui `access_profile`. Conceder USER e depois ADMIN
--      à MESMA Identity na MESMA Application passa pelas duas checagens
--      e produz DOIS acessos GRANTED simultâneos. A regra de negócio é
--      "um acesso ativo por identidade por aplicação" — o perfil é
--      atributo do acesso, não parte da identidade dele.
--
--   2. `exists()` seguido de `insert()` é TOCTOU: duas transações
--      concorrentes leem "não existe" e ambas inserem. Um importador em
--      lote é exatamente o cenário que dispara isso.
--
-- SOLUÇÃO — flag gerada NUMÉRICA + UNIQUE KEY COMPOSTA
--
-- Coluna VIRTUAL gerada `active_grant_flag` (1 quando GRANTED, NULL caso
-- contrário) e UNIQUE KEY sobre
-- (identity_public_id, application_public_id, active_grant_flag).
-- InnoDB trata cada NULL como distinto numa UNIQUE KEY, então:
--   - status = 'GRANTED'  -> flag = 1    -> no máximo 1 linha por par
--   - status = 'REVOKED'  -> flag = NULL -> quantas linhas históricas
--                            forem necessárias, sem colidir entre si nem
--                            com a linha GRANTED
--
-- POR QUE NÃO A CHAVE-TEXTO CONCATENADA DE 0013/0016
--
-- 0013 e 0016 usam `CONCAT(...)` numa coluna gerada indexada, e ali
-- funciona: as colunas de origem são VARCHAR. Aqui as colunas de origem
-- são CHAR(36) — e o MariaDB 10.11 RECUSA indexar coluna gerada cuja
-- expressão passe uma coluna CHAR por função de string:
--
--   ERROR 1901 (HY000): Function or expression '...' cannot be used in
--   the GENERATED ALWAYS AS clause of `active_grant_key`
--
-- O motivo é que a leitura de CHAR dentro de função de string depende de
-- `PAD_CHAR_TO_FULL_LENGTH`, que é sql_mode de SESSÃO — a expressão
-- deixa de ser estável entre conexões, e o índice, portanto, inválido.
-- Verificado nesta versão exata do servidor (10.11.14), pelo driver da
-- aplicação (mysql2) e não só pelo cliente de linha de comando.
--
-- A flag numérica evita a função de string por completo: o único termo
-- gerado é derivado do ENUM `status`, e os dois public_id entram
-- DIRETAMENTE na UNIQUE KEY, sem transformação. A garantia é a mesma, e
-- o índice ainda serve de índice de busca por (identity, application).
--
-- O `access_profile` fica DELIBERADAMENTE FORA da chave. Incluí-lo
-- reintroduziria exatamente o furo 1. Trocar de perfil passa a ser
-- revoke + grant na mesma transação — nunca dois GRANTED coexistindo.
--
-- PREFLIGHT OBRIGATÓRIO ANTES DE APLICAR
--
-- Se já existirem duplicatas GRANTED, o ALTER falha com ER_DUP_ENTRY
-- (errno 1062) e a mensagem crua do MariaDB não diz QUAIS linhas
-- colidem. Rode antes:
--
--     node dist/cli/preflight-application-access-uniqueness.js
--
-- Ele lista cada (identity, application) duplicado e sai com código 1
-- quando encontra alguma. A regra de "uma instrução executável por
-- arquivo" (assertSingleStatement) impede embutir a verificação aqui —
-- por isso ela é um CLI próprio, e não um segundo statement.
--
-- Exatamente UMA instrução executável neste arquivo (assertSingleStatement).
--
-- NÃO EXECUTAR AUTOMATICAMENTE NESTA FATIA.

ALTER TABLE application_accesses
    ADD COLUMN active_grant_flag TINYINT UNSIGNED GENERATED ALWAYS AS (
        CASE WHEN status = 'GRANTED' THEN 1 ELSE NULL END
    ) VIRTUAL
        COMMENT 'Coluna gerada, uso exclusivo de uk_app_access_active_grant abaixo - nunca lida/gravada diretamente pela aplicacao. 1 quando status = GRANTED, NULL caso contrario. Flag numerica (e nao chave-texto concatenada como em 0013/0016) porque identity_public_id/application_public_id sao CHAR(36) e o MariaDB 10.11 recusa indexar coluna gerada que passe CHAR por funcao de string (ERROR 1901).',
    ADD UNIQUE KEY uk_app_access_active_grant (identity_public_id, application_public_id, active_grant_flag)
        COMMENT 'Garante, NO PROPRIO BANCO e sem janela de corrida (TOCTOU), no maximo 1 linha GRANTED por (identity_public_id, application_public_id). Linhas REVOKED tem active_grant_flag NULL e nunca colidem. access_profile fica FORA da chave de proposito: a regra e um acesso ativo por identidade por aplicacao, e o perfil e atributo do acesso. Troca de perfil = revoke + grant transacional.';
