-- Migration: 0018_seed_pctec_helpdesk_application
-- Direção: UP
-- Motor: MariaDB 10.11, InnoDB, utf8mb4, utf8mb4_unicode_520_ci
--
-- Referência: fundação do importador Helpdesk -> Ingressa (v0.8.x),
-- item 2 da task. Mesmo padrão de 0007 (PCTEC_INGRESSA) e 0014
-- (PCTEC_PORTAL).
--
-- `PCTEC_HELPDESK` como Application própria do catálogo, conforme
-- ADR-031 §1 ("cada produto consumidor possuir Application própria") —
-- nunca reaproveita `PCTEC_PORTAL` nem `PCTEC_INGRESSA`. Um usuário do
-- Helpdesk que não tenha ApplicationAccess(PCTEC_HELPDESK) não passa a
-- ter acesso ao Portal por tabela nenhuma, e vice-versa.
--
-- public_id determinístico pelo mesmo raciocínio de 0007/0014: é
-- metadado técnico estável da plataforma (não dado pessoal), precisa
-- ser o MESMO valor entre dev/test/produção para que CLI e testes de
-- integração o referenciem sem consultar o banco antes, e evita que
-- dois ambientes gerem public_ids diferentes para a mesma aplicação
-- conceitual. UUID v4 gerado uma única vez, não derivado de dado.
--
-- NATUREZA: CONFIGURAÇÃO DE PLATAFORMA, NÃO DADO DE LOTE
--
-- Esta linha NÃO pertence a nenhum `import_batch` e NÃO é removida pelo
-- rollback de lote nenhum. O rollback de dados de importação compensa
-- Identities, Memberships, ExternalReferences e ApplicationAccesses —
-- nunca o catálogo de aplicações. Ver
-- docs/import/ROLLBACK-COMPENSACOES.md.
--
-- Idempotência: NÃO é responsabilidade deste SQL (mesmo princípio já
-- documentado em 0007 e reafirmado em 0014) — a idempotência operacional
-- é fornecida pelo MigrationRunner, que só executa o que ainda não está
-- em `schema_migrations`. Nenhuma cláusula de "ignorar duplicidade"
-- aqui; um estado divergente pré-existente deve FALHAR explicitamente
-- (violação de UNIQUE KEY), nunca ser mascarado.
--
-- O que isso protege, concretamente: se alguém já tiver inserido à mão
-- uma linha com este `public_id` mas com `code`/`name`/`status`
-- diferentes, o INSERT normal aborta com ER_DUP_ENTRY e o runner nem
-- chega a marcar 0018 como aplicada — o operador é obrigado a olhar. Com
-- `INSERT IGNORE`, a divergência viraria no-op silencioso, a migration
-- seria registrada como aplicada, e a Application ficaria com o code ou
-- o status errado até alguém tropeçar nisso muito mais tarde.
--
-- Exatamente UMA instrução executável neste arquivo (assertSingleStatement).
--
-- NÃO EXECUTAR AUTOMATICAMENTE NESTA FATIA.

INSERT INTO applications (public_id, code, name, status, version, created_at, updated_at)
VALUES ('5c7a2b91-1e6d-4f38-b7a4-000000000001', 'PCTEC_HELPDESK', 'PCTEC Helpdesk', 'ACTIVE', 1, UTC_TIMESTAMP(3), UTC_TIMESTAMP(3));
